# -*- coding: utf-8 -*-
"""PrakAlgo9

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cGKz0jNsv0661vciopR9iBU7PNKpqkS_
"""

def konversi_list_ke_tuple(input_list):
    # Menggunakan fungsi tuple() untuk mengonversi list menjadi tuple
    tuple_hasil = tuple(input_list)
    return tuple_hasil

# Contoh penggunaan
list_contoh = [1, 2, 3, 4, 5]
tuple_hasil = konversi_list_ke_tuple(list_contoh)

print("List:", list_contoh)
print("Tuple hasil konversi:", tuple_hasil)

def hitung_rata_rata(tuple_input):
    total = 0
    jumlah_elemen = 0

    for tup in tuple_input:
        for elemen in tup:
            total += elemen
            jumlah_elemen += 1

    if jumlah_elemen == 0:
        return None  # Menghindari pembagian oleh nol
    else:
        rata_rata = total / jumlah_elemen
        return rata_rata

# Contoh penggunaan
tuple_contoh = ((31,32,33),(34,35,36),(37,38,39))
rata_rata_hasil = hitung_rata_rata(tuple_contoh)

if rata_rata_hasil is not None:
    print("Tuple:", tuple_contoh)
    print("Rata-rata:", rata_rata_hasil)
else:
    print("Tidak ada elemen untuk dihitung rata-ratanya.")

print('______KEVIN______')
print('___065002300026____')

def hitung_hasil_kali(list_input):
    hasil_kali = 1

    for nilai in list_input:
        hasil_kali *= nilai

    return hasil_kali

# Contoh penggunaan
list_contoh = [2, 3, 4, 5]
hasil_kali = hitung_hasil_kali(list_contoh)

print("List:", list_contoh)
print("Hasil Kali:", hasil_kali)

def hitung_jumlah_string(list_input):
    jumlah_string = 0

    for string in list_input:
        if len(string) >= 2 and string[0] == string[-1]:
            jumlah_string += 1

    return jumlah_string

# Contoh penggunaan
list_contoh = ["aba", "xyz", "level", "radar", "python", "pop"]
jumlah_string_hasil = hitung_jumlah_string(list_contoh)

print("List:", list_contoh)
print("Jumlah String:", jumlah_string_hasil)